// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ZK3Ka3GLBNfX7wb1NZz6y
// Component: 23y1SDggi8Ko

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: nxKBKvpVYc_r/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_alpha.module.css"; // plasmic-import: ZK3Ka3GLBNfX7wb1NZz6y/projectcss
import sty from "./PlasmicNavGroup.module.css"; // plasmic-import: 23y1SDggi8Ko/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: lixJ7oSuiNeq/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: ZwlhKNz16ciL/icon

createPlasmicElementProxy;

export type PlasmicNavGroup__VariantMembers = {};
export type PlasmicNavGroup__VariantsArgs = {};
type VariantPropType = keyof PlasmicNavGroup__VariantsArgs;
export const PlasmicNavGroup__VariantProps = new Array<VariantPropType>();

export type PlasmicNavGroup__ArgsType = {};
type ArgPropType = keyof PlasmicNavGroup__ArgsType;
export const PlasmicNavGroup__ArgProps = new Array<ArgPropType>();

export type PlasmicNavGroup__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultNavGroupProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavGroup__RenderFunc(props: {
  variants: PlasmicNavGroup__VariantsArgs;
  args: PlasmicNavGroup__ArgsType;
  overrides: PlasmicNavGroup__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <Button
        className={classNames("__wab_instance", sty.button__wfDns)}
        link={`/inside-info`}
      >
        {"Inside Info"}
      </Button>
      <Button
        className={classNames("__wab_instance", sty.button___1RNDg)}
        link={`/protected-info`}
      >
        {"Protected Info"}
      </Button>
      <Button
        className={classNames("__wab_instance", sty.button___3ZrSu)}
        link={`/protected-page`}
      >
        {"Protected Page"}
      </Button>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavGroup__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavGroup__VariantsArgs;
    args?: PlasmicNavGroup__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNavGroup__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicNavGroup__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavGroup__ArgProps,
          internalVariantPropNames: PlasmicNavGroup__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavGroup__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavGroup";
  } else {
    func.displayName = `PlasmicNavGroup.${nodeName}`;
  }
  return func;
}

export const PlasmicNavGroup = Object.assign(
  // Top-level PlasmicNavGroup renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicNavGroup
    internalVariantProps: PlasmicNavGroup__VariantProps,
    internalArgProps: PlasmicNavGroup__ArgProps
  }
);

export default PlasmicNavGroup;
/* prettier-ignore-end */
