// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ZK3Ka3GLBNfX7wb1NZz6y
// Component: Hq5FXfp1OMVd

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import DefaultLayout from "../../DefaultLayout"; // plasmic-import: 3DHGFMCCchpq/component
import Nav from "../../Nav"; // plasmic-import: M7FSrNvh01Bb/component
import Logo from "../../Logo"; // plasmic-import: x-WUVb1UdtEk/component
import AuthButton from "../../AuthButton"; // plasmic-import: 1JFfF43ycoS1/component
import { ConditionGuard } from "@plasmicpkgs/plasmic-basic-components";
import NavGroup from "../../NavGroup"; // plasmic-import: 23y1SDggi8Ko/component
import Footer from "../../Footer"; // plasmic-import: MdFayujW6N0n/component

import { useScreenVariants as useScreenVariantsbByOFjTZbjEa } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: BByOFjTZbjEA/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_alpha.module.css"; // plasmic-import: ZK3Ka3GLBNfX7wb1NZz6y/projectcss
import sty from "./PlasmicProtectedInfo.module.css"; // plasmic-import: Hq5FXfp1OMVd/css

import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: IB_RYl67U9w9/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: wXhjyFdhDt7b/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: 6m0AkRk1brN4/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: LpAxg6jRC7f2/icon

createPlasmicElementProxy;

export type PlasmicProtectedInfo__VariantMembers = {};
export type PlasmicProtectedInfo__VariantsArgs = {};
type VariantPropType = keyof PlasmicProtectedInfo__VariantsArgs;
export const PlasmicProtectedInfo__VariantProps = new Array<VariantPropType>();

export type PlasmicProtectedInfo__ArgsType = {};
type ArgPropType = keyof PlasmicProtectedInfo__ArgsType;
export const PlasmicProtectedInfo__ArgProps = new Array<ArgPropType>();

export type PlasmicProtectedInfo__OverridesType = {
  root?: p.Flex<"div">;
  defaultLayout?: p.Flex<typeof DefaultLayout>;
  nav?: p.Flex<typeof Nav>;
  foreground?: p.Flex<"div">;
  h2?: p.Flex<"h2">;
  conditionGuard?: p.Flex<typeof ConditionGuard>;
  foreground2?: p.Flex<"div">;
  navGroup?: p.Flex<typeof NavGroup>;
};

export interface DefaultProtectedInfoProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProtectedInfo__RenderFunc(props: {
  variants: PlasmicProtectedInfo__VariantsArgs;
  args: PlasmicProtectedInfo__ArgsType;
  overrides: PlasmicProtectedInfo__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbByOFjTZbjEa()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <DefaultLayout
            data-plasmic-name={"defaultLayout"}
            data-plasmic-override={overrides.defaultLayout}
            className={classNames("__wab_instance", sty.defaultLayout)}
            slot={
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__w1DBe)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__zKG2)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"foreground"}
                    data-plasmic-override={overrides.foreground}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.foreground)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tiSP
                      )}
                    >
                      {"Values"}
                    </div>
                    <h2
                      data-plasmic-name={"h2"}
                      data-plasmic-override={overrides.h2}
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2
                      )}
                    >
                      {"Not just another design"}
                    </h2>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fWffK
                      )}
                    >
                      {
                        "A euismod eros a hendrerit tristique suscipit sit aptent dolor adipiscing inceptos cras ullamcorper a vivamus parturient."
                      }
                    </div>
                  </p.Stack>
                  <ConditionGuard
                    data-plasmic-name={"conditionGuard"}
                    data-plasmic-override={overrides.conditionGuard}
                    className={classNames("__wab_instance", sty.conditionGuard)}
                    condition={true}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"foreground2"}
                      data-plasmic-override={overrides.foreground2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.foreground2)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bPhhq
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__mevPk
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__vPDhW
                            )}
                          >
                            <Icon2Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__lHsz3
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__rEnSr
                              )}
                            >
                              <Icon2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__rnyF3
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ujvir
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__jbVjj
                              )}
                            >
                              {"Welcoming atmosphere"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ejHnH
                              )}
                            >
                              {
                                "Orci commodo maecenas fringilla ad nec amet tempus mattis platea eget tortor sit dolor etiam a ullamcorper varius."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__bc1Cw
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__wHshe
                            )}
                          >
                            <Icon3Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg___4N6Dn
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___02K6R
                              )}
                            >
                              <Icon2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___3Mnq0
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__q0I7V
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__jyjpr
                              )}
                            >
                              {"Tested and secure"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__hvx2R
                              )}
                            >
                              {
                                "Feugiat sapien ornare vivamus bibendum a ullamcorper feugiat faucibus feugiat blandit a per imperdiet dapibus metus ut scelerisque sagittis felis nostra per accumsan rutrum."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kxhQ
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oeWCu
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__icrs
                            )}
                          >
                            <Icon4Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__nqzkt
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__fF2Yb
                              )}
                            >
                              <Icon2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__hie2G
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__yeJh6
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__cC9Mh
                              )}
                            >
                              {"Mindful notifications"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ntg0H
                              )}
                            >
                              {
                                "Porttitor feugiat a scelerisque nullam parturient vestibulum tempor a litora suscipit arcu potenti varius venenatis venenatis dapibus fames adipiscing in in taciti."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__a4Det
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__a5O2R
                            )}
                          >
                            <Icon5Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__boD4
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__bs8Kr
                              )}
                            >
                              <Icon2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__tk9Es
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___1KHgx
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__g2DuX
                              )}
                            >
                              {"Real-time results"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__tYRr
                              )}
                            >
                              {
                                "Scelerisque facilisi at class a inceptos mi aliquet vestibulum taciti platea amet litora quisque mus parturient a mauris arcu."
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>
                  </ConditionGuard>
                  <NavGroup
                    data-plasmic-name={"navGroup"}
                    data-plasmic-override={overrides.navGroup}
                    className={classNames("__wab_instance", sty.navGroup)}
                  />
                </p.Stack>
              </p.Stack>
            }
          >
            <Nav
              data-plasmic-name={"nav"}
              data-plasmic-override={overrides.nav}
              className={classNames("__wab_instance", sty.nav)}
              states={"signedInUser"}
            />
          </DefaultLayout>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "defaultLayout",
    "nav",
    "foreground",
    "h2",
    "conditionGuard",
    "foreground2",
    "navGroup"
  ],
  defaultLayout: [
    "defaultLayout",
    "nav",
    "foreground",
    "h2",
    "conditionGuard",
    "foreground2",
    "navGroup"
  ],
  nav: ["nav"],
  foreground: ["foreground", "h2"],
  h2: ["h2"],
  conditionGuard: ["conditionGuard", "foreground2"],
  foreground2: ["foreground2"],
  navGroup: ["navGroup"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  defaultLayout: typeof DefaultLayout;
  nav: typeof Nav;
  foreground: "div";
  h2: "h2";
  conditionGuard: typeof ConditionGuard;
  foreground2: "div";
  navGroup: typeof NavGroup;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProtectedInfo__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProtectedInfo__VariantsArgs;
    args?: PlasmicProtectedInfo__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProtectedInfo__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicProtectedInfo__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProtectedInfo__ArgProps,
          internalVariantPropNames: PlasmicProtectedInfo__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProtectedInfo__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProtectedInfo";
  } else {
    func.displayName = `PlasmicProtectedInfo.${nodeName}`;
  }
  return func;
}

export const PlasmicProtectedInfo = Object.assign(
  // Top-level PlasmicProtectedInfo renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    defaultLayout: makeNodeComponent("defaultLayout"),
    nav: makeNodeComponent("nav"),
    foreground: makeNodeComponent("foreground"),
    h2: makeNodeComponent("h2"),
    conditionGuard: makeNodeComponent("conditionGuard"),
    foreground2: makeNodeComponent("foreground2"),
    navGroup: makeNodeComponent("navGroup"),

    // Metadata about props expected for PlasmicProtectedInfo
    internalVariantProps: PlasmicProtectedInfo__VariantProps,
    internalArgProps: PlasmicProtectedInfo__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicProtectedInfo;
/* prettier-ignore-end */
